name: Build, Push, and Deploy to Kubernetes

on:
  push:
    branches:
      - release

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: thyrail/rock-paper-scissors
          tags: type=sha,prefix=,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  update-manifest:
    name: Update Kubernetes Manifest
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout k8s-config repo
        uses: actions/checkout@v4
        with:
          repository: Thyrail/thyrail-k8s-config 
          ssh-key: ${{ secrets.CONFIG_REPO_DEPLOY_KEY }}
          ref: master

      - name: Update deployment.yaml with new image tag
        run: |
          # Der Tag wird aus dem vorherigen Job übergeben
          NEW_TAG="thyrail/rock-paper-scissors:${{ needs.build-and-push.image_tag }}"
          # Wir verwenden 'sed', um die image-Zeile zu finden und zu ersetzen
          sed -i "s|image:.*|image: ${NEW_TAG}|g" apps/rock-paper-scissors/deployment.yaml

      - name: Commit and push manifest changes
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'bot@github.com'
          git add apps/rock-paper-scissors/deployment.yaml
          # Wir committen nur, wenn es eine echte Änderung gab
          git diff --staged --quiet || git commit -m "Deploy new image for rps-app: ${{ needs.build-and-push.image_tag }}"
          # Wir pushen die Änderung zurück in den master-Branch des Konfig-Repos
          git push origin master