name: Build, Push, and Deploy

on:
  push:
    branches:
      - release

jobs:
  build-and-deploy:
    name: Build, Push and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: thyrail/rock-paper-scissors:${{ github.sha }}

      - name: Checkout k8s-config repo
        uses: actions/checkout@v4
        with:
          repository: Thyrail/thyrail-k8s-config
          ssh-key: ${{ secrets.CONFIG_REPO_DEPLOY_KEY }}
          ref: master

      - name: Update deployment.yaml with new image digest
        run: |
          IMAGE_DIGEST="thyrail/rock-paper-scissors@${{ steps.build.outputs.digest }}"
          echo "Updating to new image: ${IMAGE_DIGEST}"
          sed -i 's|^\(\s*image:\s*\).*|\1'"${IMAGE_DIGEST}"'|' apps/rock-paper-scissors/deployment.yaml
          echo "Content of deployment.yaml after update:"
          cat apps/rock-paper-scissors/deployment.yaml

      - name: Commit and push manifest changes
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'bot@github.com'
          git add apps/rock-paper-scissors/deployment.yaml
          git diff --staged --quiet || git commit -m "Deploy new image for rps-app: ${{ github.sha }}"
          git push origin master